aksio-insurtech/ApplicationModel

Source/DotNET/Applications/HostBuilderExtensions.cs, Source/DotNET/Applications/ModuleInitializer.cs
- Adding a `ModuleInitializer` to perform all the exclusion of assemblies for the type discovery system.
=> Add module initializer for hooking up assembly prefixes to exclude

Source/DotNET/CQRS/Queries/ClientObservable.cs
- Fixed null reference exception for duplicate `SendAsync` call caused by an error during merging.
=> Fixing merge error

Source/DotNET/Applications/HostBuilderExtensions.cs
- Removing the `MicroserviceId` and `MicroserviceName` from the `.UseAksio()` setup call. These were optional and not used for anything.
=> Remove MicroserviceId and Name from setup - its not used for anything

Source/DotNET/Applications/ApplicationBuilderExtensions.cs
- Removing `.UseWebSockets()` call from the `.UseAksio()` extension method, as this needs to be explicitly called from the applications themselves in the right order.
=> Remove UseWebSockets() - as this needs to be controlled by the apps themselves

Source/DotNET/CQRS/Queries/QueryActionFilter.cs, Source/DotNET/CQRS/Queries/QueryActionFilterLogMessages.cs
- Adding trace logging for seeing WebSocket HTTP headers for debugging purposes.
=> Adding trace logging for seeing WebSocket info

Source/JavaScript/Applications/queries/useQuery.ts
- Await the result of the query when doing a refresh. The operation is async.
=> Await the result of the query on refresh

Documentation/cqrs/without-wrappers.md, Source/DotNET/ProxyGenerator/SourceGenerator.cs, Source/DotNET/ProxyGenerator/Syntax/MethodSymbolExtensions.cs, Source/DotNET/ProxyGenerator/Syntax/WellKnownAttributeExtensions.cs
- Proxy generator will now ignore any ASP.NET controller actions marked with `[AspNetResult]` attribute, as intended.
=> Proxy generator will now ignore AspNetResult commands and queries

Source/DotNET/Applications/ServiceCollectionExtensions.cs
- Changed the automatic hookup of assembly parts that holds controllers to discover based on implementations of `ControllerBase` and not `Controller`, which is more accurate as pure API controllers should inherit from `ControllerBase`.
=> Changing to discover assemblies with implementations of ControllerBase in it, not just Controller

Source/JavaScript/Applications/queries/ObservableQueryFor.ts, Source/JavaScript/Applications/queries/QueryResult.ts
- Fixed `ObservableQueryFor` and `QueryFor` for frontend to make sure it returns an array for enumerable types, even if the server returns an object. It will set it to an empty array if that is the case. That way it is consistently the correct type at least.
=> Make sure we never return an object literal for something that is an array

Source/DotNET/Applications/HostBuilderExtensions.cs, Source/DotNET/Applications/Identity/ClientPrincipal.cs, Source/DotNET/Applications/Identity/ClientPrincipalClaim.cs, Source/DotNET/Applications/Identity/IdentityProviderEndpoint.cs, Source/DotNET/Applications/Identity/IdentityProviderEndpointExtensions.cs, Specifications/Applications/Identity/for_IdentityProviderEndpoint/given/a_valid_identity_request.cs, Specifications/Applications/Identity/for_IdentityProviderEndpoint/given/an_identity_provider_endpoint.cs, Specifications/Applications/Identity/for_IdentityProviderEndpoint/when_handling/and_claims_are_missing.cs, Specifications/Applications/Identity/for_IdentityProviderEndpoint/when_handling/and_identity_id_header_is_missing.cs, Specifications/Applications/Identity/for_IdentityProviderEndpoint/when_handling/and_identity_is_valid_with_multiple_roles.cs, Specifications/Applications/Identity/for_IdentityProviderEndpoint/when_handling/and_identity_name_header_is_missing.cs, Specifications/Applications/Identity/for_IdentityProviderEndpoint/when_handling/and_principal_header_is_missing.cs, Specifications/Applications/Identity/for_IdentityProviderEndpointExtensions/when_adding_identity_provider/and_there_are_multiple_providers.cs, Specifications/Applications/Identity/for_IdentityProviderEndpointExtensions/when_adding_identity_provider/and_there_is_one_provider.cs
- Fixing the `IdentityProviderEndpoint` to handle multiple claims with same type.
- Refactoring `IdentityProviderEndpoint` and setup to be more testable.
- Added specs for `IdentityProviderEndpoint` and setup code.
=> Fixing so that we can have multiple of same claim type

Source/DotNET/Applications/Identity/IdentityProviderEndpointExtensions.cs, Specifications/Applications/Identity/for_IdentityProviderEndpointExtensions/when_adding_identity_provider/and_there_are_no_providers.cs
- The previous version crashed on startup if used in a solution without an identity provider.
=> Fix for crash that occured when no identity providers are present

Source/JavaScript/Applications/queries/IObservableQueryFor.ts, Source/JavaScript/Applications/queries/ObservableQueryFor.ts, Source/JavaScript/Applications/queries/useObservableQuery.ts
- Fixing the `OnNextResult` generic definition. It didn't include the generic parameter properly and forcing one to have to cast the result to `QueryResult<TDataType>`. Now it will be correct data type.
=> Making the callback for subscribe generic to get the actual data type

Source/DotNET/CQRS.MongoDB/MongoDBCollectionExtensions.cs
- Adding `delete` to the change stream filter for `.Observer()` on Mongo collections.
=> Adding delete to the filter of things we watch for Mongo

Source/DotNET/CQRS.MongoDB/MongoDBCollectionExtensions.cs
- Fixing the `.Observe()` method for a collection of items to remove items that have a MongoDB change stream update of delete.
=> Adding support for actually removing an item when using .Observe() on Mongo collections

Source/DotNET/CQRS/Queries/ClientObservable.cs
- Handling exceptions if serialization to UTF8 for the WebSocket connections.
- Printing any exceptions that occur during serialization or sending data to client over WebSockets.
=> Exception handling for JSON serializer + outputting error to console if any

Source/DotNET/CQRS.MongoDB/MongoDBCollectionExtensions.cs
- `OnNext()` was never called on the observable given to the `MongoDBCollectionExtensions` when observing changes for `ClientObservables`.
=>  "Add version v1.5.6 to changelog"

Directory.Packages.props
Update fundamentals to 1.6.1 to get the new ToCamelCase method
This is especially needed for the Proxy Generation.
=> Update fundamentals to 1.6.1 to get the new ToCamelCase method

Directory.Packages.props, Specifications/Applications/when_converting_to_camel_case.cs
To avoid the broken ToCamelCase implementation.  Added the tests to ensure we don't use the ACRONYM based ToCamelCase (It breaks all the existing read models, etc).
=> Revert to Fundamentals 1.6.0 t

Source/DotNET/ProxyGenerator/Templates/ObservableQuery.hbs
useObservableQuery now always returns an object, never an enumerable.
=> Remove enumerable for observable query

Source/DotNET/ProxyGenerator/Templates/ObservableQuery.hbs
Didn't remove the Array, only the branching part.
=> Actually remove the Array return for useObservableQuery

Source/DotNET/ProxyGenerator/Syntax/TypeSymbolExtensions.cs
Look for the interface rather than the concrete type.  Allows client implementations to be generated.
=> Change the IsObservableClient check in proxy generation.
